apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 10
  selector: 
    matchLabels: 
      app: hello
      tier: hello
  template:
    metadata:
      labels:
        app: hello
        tier: hello
    spec:
      containers:
      - name: hello
        image: myregistry.com/root/cicd-pipeline/hello:jenkins-ENV_BUILD_ID
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: hello
      imagePullSecrets:
      - name: regcred
